spring.application.name=Server_Licenta
server.port=9001
spring.rabbitmq.dynamic=true

# Add "jdbc:" at the start and keep the rest
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres

# Extract the username from the part before the ":"
spring.datasource.username=postgres.dqxlpviizbfilkinbsda

# Use the password you set when creating the project
spring.datasource.password=BvjULPWYD6rVgfwR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect